### ISSUE TITLE
Difficulty Settings

### ISSUE THREAD

**Issue by Zachattack525** [Discookie/ShieldMod#10]
After compiling, installing, and playing a few games, i wanted to change some values to get this mod to be able to break my average 98% hit rate, but when i tried to run htp.js, but when i ran it, it told me that there was an error, line 198, character 1, saying that "document" was undefined. fix?

**Comment by Discookie** [comment]
For Stable, the way to change the difficulty is to edit the first few lines of `Hard ShieldVR.lua`.
For Dev, the settings folder is hidden inside `src/settings/diff.lua` (recently moved up to just `settings/game.lua`).

The `dynamic/htp.js` is just the file that handles rendering the How-To-Play screen.
The values it displays are inside `dynamic/diff.js` (these are just for the difficulty on the HTP screen, they don't interact with the game).
In Dev, the values displayed are in `htp/dynamic/diff.js` (or recently, `settings/display.js`).

There should be a program that lets you manage difficulty easier, since there are many settings, but most are only for fine-tuning. But that is part of a separate issue (an issue that is now #11).

Commit where the settings were moved is bfcb80a.

(The JavaScript error goes away if you open not the JS ile, but the `howtoplay_EN.html` screen)
